### ISSUE TITLE
Feature Request: Get templates by slug

### ISSUE THREAD

**Issue by AustinGil** [dcooney/wordpress-ajax-load-more#117]
I would really love to see the custom templates support custom slugs. Right now, using the custom templates (or "Repeaters") each new template gets an automatically generated template name (template_1). 

For the most part, this is ok, but I develop on a dev site and push changes to the live site. I also use the shortcodes from this plugin in my templates. If one of these become out of sync, it's likely that my templates will break. 

I think it's a good idea, but I also can understand if you have more pressing things. Would love to see it though :)

**Comment by dcooney** [comment]
@Stegosource I like this idea. I just need to think through how renaming the template would work since the slug is essentially the ID.

I think a lot of users get around this by using the (Theme Repeater)[https://connekthq.com/plugins/ajax-load-more/add-ons/theme-repeaters/] addon. That way they can control the templates right in their themes.

Thanks for your thought on this, i've added it to me enhancement list.

**Comment by Stegosource** [comment]
Oh damn, I bought the wrong add-on. I didnt see that one. That would have made everything SOOO much easier. Haha. Is it possible to switch the licenses or do I have to purchase the other add-on?

**Comment by dcooney** [comment]
Hey Austin,
I got your email, but you entered an incorrect email so I cannot respond.

**Comment by Stegosource** [comment]
Oh really? Man, I am blowing it. I just submitted again and got the confirmation notification.
