### ISSUE TITLE
duplicate latest loaded post if a new post inserted to databases 

### ISSUE THREAD

**Issue by snhasani** [dcooney/wordpress-ajax-load-more#124]
Hi.
We have issue with loaded post order in special situation. after plugin loaded some post and user stop to scrolling, if a new post inserted to database at this period, and then when user continued scrolling to bottom, plugin duplicated last post which loaded on previous time and inserted of it in top of latest series of loaded posts.

**Comment by dcooney** [comment]
@snhasani This makes sense because Ajax Load More uses `offset` param of `WP_Query` to determine post display. Not really sure what you could do about this other than use the Cache add-on to serve cached pages to users and then clear the cache at intervals through the day.
https://connekthq.com/plugins/ajax-load-more/add-ons/cache/

Depending on how often you post Im not sure that's a good idea though.

**Comment by snhasani** [comment]
@dcooney We can not use cache. We publish at least 150 posts each day 😄 
If you can add a callback when ajax-load-more fetched post right before DOM updating, we can handled post inserting to DOM.

**Comment by dcooney** [comment]
Wow, that's incredible.
Would the `alm_query_args` filter help at all?
https://connekthq.com/plugins/ajax-load-more/docs/filter-hooks/#alm_query_args
