### ISSUE TITLE
post_type='attachment' doesn't seem to be returning any results.

### ISSUE THREAD

**Issue by jakeleboeuf** [dcooney/wordpress-ajax-load-more#61]
Is this post type not available?

**Comment by dcooney** [comment]
Not officially supported. Did you try post_type="attachment" and it did not work?

**Comment by thepixelstack** [comment]
I know this is an old thread, but I just wanted to add to it. Recently had the same issue as OP and not sure if it was ever resolved by them. This is caused by the 'post_status' field in WP. Attachment files have a status of 'inherit', not 'published'. So in ALM, unless you include this within the custom arguments parameter, it won't work for attachments because post status defaults to published..hope that helps!

**Comment by dcooney** [comment]
You could also use the [alm_modify_query_args()](https://connekthq.com/plugins/ajax-load-more/docs/filter-hooks/#alm_modify_query_args) filter to update the post_status.

For security reason `posts_status` has been set to 'publish' by default.

Im going to put together an example of attachments one day soon.
